version: '3'
services:
  web:
    build: .
    container_name: ai-hub-v1.1
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
  mcp_server:
    build: ./scripts/PDFMathTranslate
    container_name: mcp_server-v0.1
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./scripts/PDFMathTranslate:/app
